output = "reports/unbalanced-ratio.md"

rng = 42
n_simulations = 10_000
buckets = [10, 20, 50, 100]

[sample]
alpha = 0.05  # Type I error rate for sample size calculation and estimation of power
power = 0.8  # Reference power for sample size calculation
ratio = 0.25  # Treatment-to-control allocation ratio
rel_diff_default = 0.05  # Reference uplift for sample size calculation in A/A simulations

[control]
mean = 1.0
top_users = 0.3  # Top X share of users
top_value = 0.7  # Create Y share of value

[[treatments]]
name = "A/A 0%: +5% top, -5% bottom (relative to total)"
rel_diff_top = 0.05
rel_diff_bottom = -0.05

[[treatments]]
name = "A/A 0%: -5% top, +5% bottom (relative to total)"
rel_diff_top = -0.05
rel_diff_bottom = 0.05

[[treatments]]
name = "A/B +5%: +3.5% top, +1.5% bottom (relative to total)"
rel_diff_top = 0.035
rel_diff_bottom = 0.015

[[treatments]]
name = "A/B +5%: +5% top, 0% bottom (relative to total)"
rel_diff_top = 0.05
rel_diff_bottom = 0.0

[[treatments]]
name = "A/B +5%: 0% top, +5% bottom (relative to total)"
rel_diff_top = 0.0
rel_diff_bottom = 0.05

[[user_tests]]
name = "Welch's t-test"
path = "tea_tasting.Mean"
args = [ "value" ]
kwargs = { use_t = true, equal_var = false }

[[user_tests]]
name = "Student's t-test"
path = "tea_tasting.Mean"
args = [ "value" ]
kwargs = { use_t = true, equal_var = true }

[[user_tests]]
name = "Z-test (unpooled)"
path = "tea_tasting.Mean"
args = [ "value" ]
kwargs = { use_t = false, equal_var = false }

[[user_tests]]
name = "Mann–Whitney U"
path = "tea_tasting.MannWhitneyU"
args = [ "value" ]
kwargs = { correction = true }

[[bucket_tests]]
name = "Welch's t-test"
path = "tea_tasting.RatioOfMeans"
args = [ "value", "users" ]
kwargs = { use_t = true, equal_var = false }

[[bucket_tests]]
name = "Student's t-test"
path = "tea_tasting.RatioOfMeans"
args = [ "value", "users" ]
kwargs = { use_t = true, equal_var = true }

[[bucket_tests]]
name = "Z-test (unpooled)"
path = "tea_tasting.RatioOfMeans"
args = [ "value", "users" ]
kwargs = { use_t = false, equal_var = false }

[[bucket_tests]]
name = "Mann–Whitney U"
path = "tea_tasting.MannWhitneyU"
args = [ "value_per_user" ]
kwargs = { correction = true }
